name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    # Ajoutez ici vos autres assets si besoin (images par exemple)
    - assets/images/logo/google_calendar.png
    - assets/images/logo/google_meet.png
    - assets/images/logo/microsoft-teams.png
    - assets/images/logo/gitlab.png
    - assets/images/logo/link.png
    - assets/images/logo/books.png
    - assets/images/logo/next_icon.png
    - assets/images/logo/notion.png
    - assets/images/avatar/avatar.jpg
    - assets/images/avatar/avatar1.jpg
    - assets/images/avatar/avatar2.jpg
    - assets/images/avatar/avatar3.jpg

  fonts:
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
    - family: Rotunda
      fonts:
        - asset: assets/fonts/rotunda/Fontspring-DEMO-4a-rotunda-regular.otf
        - asset: assets/fonts/rotunda/Fontspring-DEMO-5a-rotunda-medium.otf
          weight: 500
        - asset: assets/fonts/rotunda/Fontspring-DEMO-6a-rotunda-bold.otf
          weight: 700
